// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARsPsLXsk0QcFKgpqYY4D42ZFzmoge6sQ',
    appId: '1:101022139396:web:ed68935b700fbe4ab0e151',
    messagingSenderId: '101022139396',
    projectId: 'project-dsa-app',
    authDomain: 'project-dsa-app.firebaseapp.com',
    storageBucket: 'project-dsa-app.appspot.com',
    measurementId: 'G-G3YHC0MBL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvN-n8VfXRNFHQQnm6ASdGL46lV6vK61w',
    appId: '1:101022139396:android:1ff5440787fe4a9cb0e151',
    messagingSenderId: '101022139396',
    projectId: 'project-dsa-app',
    storageBucket: 'project-dsa-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADYhFjnX2U41QDZrrxg66Dd_1bKlKOSYw',
    appId: '1:101022139396:ios:1b4e1881a13874cab0e151',
    messagingSenderId: '101022139396',
    projectId: 'project-dsa-app',
    storageBucket: 'project-dsa-app.appspot.com',
    iosBundleId: 'com.example.projectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADYhFjnX2U41QDZrrxg66Dd_1bKlKOSYw',
    appId: '1:101022139396:ios:1b4e1881a13874cab0e151',
    messagingSenderId: '101022139396',
    projectId: 'project-dsa-app',
    storageBucket: 'project-dsa-app.appspot.com',
    iosBundleId: 'com.example.projectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARsPsLXsk0QcFKgpqYY4D42ZFzmoge6sQ',
    appId: '1:101022139396:web:fbda7ccaf2cad923b0e151',
    messagingSenderId: '101022139396',
    projectId: 'project-dsa-app',
    authDomain: 'project-dsa-app.firebaseapp.com',
    storageBucket: 'project-dsa-app.appspot.com',
    measurementId: 'G-YVZFKD4QWD',
  );
}
